import com.palantir.gradle.gitversion.VersionDetails
import java.net.URI

plugins {
    `java-library`
    `maven-publish`
    id("net.neoforged.moddev") version "2.0.140"
    id("com.palantir.git-version") version "4.0.0"
    idea
}

tasks.named<Wrapper>("wrapper") {
    distributionType = Wrapper.DistributionType.BIN
}

val mod_version: String by project
val mod_group_id: String by project
val mod_id: String by project
val mod_name: String by project
val mod_license: String by project
val neo_version: String by project
val parchment_mappings_version: String by project
val parchment_minecraft_version: String by project
val minecraft_version: String by project
val minecraft_version_range: String by project
val loader_version_range: String by project

group = mod_group_id

// TODO: Make this work outside of a git context.
val versionDetails: groovy.lang.Closure<VersionDetails> by extra
var details = versionDetails()

// TODO: Palantir doesn't let us filter for v prefixes on tags, this could cause issues if we tag anything else.
//       this plugin isn't perfect, but it'll do in the short term.
val tagVersion = Regex("""\d+(\.\d+)+(-\w+)?""").find(details.lastTag)?.value ?: "1.0.0"

// Without - metadata for dev builds
val strippedTagVersion = Regex("""\d+(\.\d+)+""").find(details.lastTag)?.value ?: "1.0.0"

if (details.commitDistance == 0 && details.isCleanTag) {
    version = tagVersion
} else if (details.branchName != null) {
    version = "$strippedTagVersion.${details.commitDistance}-${details.branchName.replace("/", "-")}+${details.gitHash}"
} else {
    version = "$strippedTagVersion.${details.commitDistance}-dev+${details.gitHash}"
}


repositories {
    maven {
        name = "Rover656 Maven"
        url = uri("https://maven.rover656.dev/releases")
        content {
            includeGroup("com.enderio")

            // Mirrors
            includeGroup("dev.gigaherz.graph")
        }
    }

    maven {
        name = "ModMaven"
        url = uri("https://modmaven.dev")
        content {
            includeGroup("mezz.jei")
        }
    }

    mavenLocal()
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

// Include resources generated by data generators.
sourceSets {
    main {
        resources {
            srcDir("src/generated/resources")
        }
    }

    create("datagen") {
        compileClasspath += sourceSets["main"].output
    }
}

configurations {
    val datagenImplementation by getting { extendsFrom(configurations["implementation"]) }
    val datagenCompileOnly by getting { extendsFrom(configurations["compileOnly"]) }
    val datagenRuntimeOnly by getting { extendsFrom(configurations["runtimeOnly"]) }
    val datagenAnnotationProcessor by getting { extendsFrom(configurations["annotationProcessor"]) }
}

neoForge {
    version = neo_version

    addModdingDependenciesTo(sourceSets["datagen"])

    parchment {
        mappingsVersion = parchment_mappings_version
        minecraftVersion = parchment_minecraft_version
    }

    mods {
        create(mod_id) {
            sourceSet(sourceSets["datagen"])
            sourceSet(sourceSets["main"])
        }
    }

    runs {
        create("client") {
            client()
        }

        create("server") {
            server()
            programArgument("--nogui")
        }

        create("data") {
            data()
            programArguments.addAll(
                "--mod", mod_id,
                "--all",
                "--output", file("src/generated/resources/").absolutePath,
                "--existing", file("src/main/resources/").absolutePath,
            )
        }

        configureEach {
            systemProperty("forge.logging.markers", "REGISTRIES")
            logLevel = org.slf4j.event.Level.DEBUG
            loadedMods.add(neoForge.mods[mod_id])
        }
    }
}

// Sets up a dependency configuration called 'localRuntime'.
// This configuration should be used instead of 'runtimeOnly' to declare
// a dependency that will be present for runtime testing but that is
// "optional", meaning it will not be pulled by dependents of this mod.
val localRuntime by configurations.creating
configurations.runtimeClasspath { extendsFrom(localRuntime) }

dependencies {
    // JEI
    compileOnly(libs.bundles.jeiApi)
    localRuntime(libs.bundles.jei)

    implementation(libs.endercore)
    implementation(libs.enderio)
}

val generateModMetadata = tasks.register<ProcessResources>("generateModMetadata") {
    val replaceProperties = mapOf(
        "minecraft_version" to minecraft_version,
        "minecraft_version_range" to minecraft_version_range,
        "neo_version" to neo_version,
        "loader_version_range" to loader_version_range,
        "mod_id" to mod_id,
        "mod_name" to mod_name,
        "mod_license" to mod_license,
        "mod_version" to version,
        "enderio_version_range" to libs.versions.enderio.get(),
    )
    inputs.properties(replaceProperties)
    expand(replaceProperties)
    from("src/main/templates")
    into("build/generated/sources/modMetadata")
}

sourceSets["main"].resources.srcDir(generateModMetadata)
neoForge.ideSyncTask(generateModMetadata)

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
}

idea {
    module {
        isDownloadSources = true
        isDownloadJavadoc = true
    }
}

tasks.register<Jar>("sourcesJar") {
    archiveClassifier.set("sources")
    from(sourceSets["main"].allJava)
}

tasks.build {
    dependsOn(tasks["sourcesJar"])
}

publishing {
    publications {
        create<MavenPublication>(project.name) {
            groupId = "com.enderio"
            artifactId = project.name
            version = "${project.version}"

            from(components["java"])
            artifact(tasks["sourcesJar"])

            pom {
                name.set("Endergy")
                description.set("Ender IO - Endergy Addon")
                url.set("https://github.com/Team-EnderIO/Endergy")

                licenses {
                    license {
                        name.set("Unlicense")
                        url.set("https://github.com/Team-EnderIO/Endergy/blob/dev/1.21.1/LICENSE.txt")
                    }
                }

                scm {
                    url.set("https://github.com/Team-EnderIO/Endergy.git")
                }
            }
        }
    }

    repositories {
        if (System.getenv("RVR_MAVEN_USER") != null) {
            maven {
                name = "Rover656"
                url = URI("https://maven.rover656.dev/releases")
                credentials {
                    username = System.getenv("RVR_MAVEN_USER")
                    password = System.getenv("RVR_MAVEN_PASSWORD")
                }
            }
        }
    }
}