plugins {
    
    id 'java'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.0.37]'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
}

version = "${minecraft_version}-${mod_version}-${environment}"
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
   mappings channel: 'parchment', version: "${parchment_version}-${minecraft_version}"
   copyIdeResources = true


    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        server {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        data {
            workingDirectory project.file('run')
            property 'forge.logging.console.level', 'debug'
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"

            args '--mod', mod_id, '--all',
                 '--output', file('src/generated/resources/').absolutePath,
                 '--existing', file('src/main/resources/').absolutePath

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }
    }
}

sourceSets {
    main {
        resources { srcDir 'src/generated/resources' }
    }
}

repositories {
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven {
        name = "Tterrag Maven"
        url = "https://maven.tterrag.com/"
    }
    maven {
        name = "Rover656 Maven"
        url = "https://maven.rover656.dev/releases"
    }
    maven {
        name = "ModdingX"
        url = "https://maven.moddingx.org"
    }
    mavenCentral()
}

dependencies {
     minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    // Mixin
    annotationProcessor("org.spongepowered:mixin:0.8.5:processor")

    // EnderIO
    compileOnly fg.deobf("com.enderio:EnderIO:${enderio_version}:api")
    implementation fg.deobf("com.enderio:EnderIO:${enderio_version}")
    runtimeOnly fg.deobf("dev.gigaherz.graph:GraphLib3:3.0.4")

    // Registrate
    implementation fg.deobf("com.tterrag.registrate:Registrate:${registrate_version}")

    // JEI
    compileOnly fg.deobf("mezz.jei:jei-1.20.1-common-api:${jei_version}")
    compileOnly fg.deobf("mezz.jei:jei-1.20.1-forge-api:${jei_version}")
    runtimeOnly fg.deobf("mezz.jei:jei-1.20.1-forge:${jei_version}")
}

tasks.withType(ProcessResources).configureEach {
    def replaceProperties = [
        minecraft_version   : minecraft_version,
        forge_version       : forge_version,
        loader_version_range: loader_version_range,
        mod_id              : mod_id,
        mod_name            : mod_name,
        mod_license         : mod_license,
        mod_version         : mod_version,
        enderio_version     : enderio_version,
        jei_version         : jei_version,
    ]
    inputs.properties replaceProperties
    filesMatching('META-INF/mods.toml') {
        expand replaceProperties
    }
}

jar {
    manifest {
        attributes([
            "Specification-Title"     : mod_id,
            "Specification-Version"   : "1",
            "Implementation-Title"    : project.name,
            "Implementation-Version"  : "${version}",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
        ])
    }
}

jar.finalizedBy('reobfJar')

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 17
}

