org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Minecraft
minecraft_version=1.20.1
forge_version=47.1.1
loader_version_range=[47,)

# Parchment 
parchment_version=2023.09.03

## Mod Properties
mod_id=enderio_endergy
mod_name=Ender IO - Endergy
mod_license=CC0
mod_group_id=com.enderio
mod_version=6.0.0
environment=Alpha

## Dependencies
enderio_version=1.20.1-6.2.18-beta
jei_version=15.2.0.22
registrate_version=MC1.20-1.3.3