[versions]
enderio = "6.2.18-beta-all"
jeiVersion = "15.20.0.129"

[libraries]
endercore = { group = "com.enderio", name = "endercore", version.ref = "enderio" }
enderio = { group = "com.enderio", name = "enderio", version.ref = "enderio" }
jeiCommonApi = { group = "mezz.jei", name = "jei-1.20.1-common-api", version.ref = "jeiVersion" }
jeiForgeApi  = { group = "mezz.jei", name = "jei-1.20.1-forge-api",  version.ref = "jeiVersion" }
jeiCommon    = { group = "mezz.jei", name = "jei-1.20.1-common",     version.ref = "jeiVersion" }
jeiForge     = { group = "mezz.jei", name = "jei-1.20.1-forge",      version.ref = "jeiVersion" }

[bundles]
jeiApi = ["jeiCommonApi", "jeiForgeApi"]
jei    = ["jeiCommon", "jeiForge"]