[versions]
enderio = { strictly = "[8.2.6-beta,)", prefer = "8.2.6-beta" }
jeiVersion = "19.25.0.321"

[libraries]
endercore = { group = "com.enderio", name = "endercore", version.ref = "enderio" }
enderio = { group = "com.enderio", name = "enderio", version.ref = "enderio" }
jeiCommonApi = { group = "mezz.jei", name = "jei-1.21.1-common-api", version.ref = "jeiVersion" }
jeiNeoforgeApi = { group = "mezz.jei", name = "jei-1.21.1-neoforge-api", version.ref = "jeiVersion" }
jeiCommon = { group = "mezz.jei", name = "jei-1.21.1-common", version.ref = "jeiVersion" }
jeiNeoforge = { group = "mezz.jei", name = "jei-1.21.1-neoforge", version.ref = "jeiVersion" }

[bundles]
jeiApi = ["jeiCommonApi", "jeiNeoforgeApi"]
jei = ["jeiCommon", "jeiNeoforge"]
